# This is an OpenAPI Specification (https://swagger.io/specification/)
# for the NHAIS Adaptor API
# owned by NHS Digital (https://digital.nhs.uk/)
openapi: "3.0.0"
info:
  version: "{VERSION}"
  title: NHAIS Adaptor (FHIR) API
  description: |
    ## Overview
    Use this API to access the NHAIS Adaptor API

    You can:
    * Accept a new patient
    * Amend an existing patient's demographics
    * Request a Removal for a patient who has moved out of area
    * Request a Deduction for a supported reason

    The NHAIS Adaptor does not store any patient demograpic data and no GET operations are supported.

    The API is based on the [Personal Demographics Service API](https://github.com/NHSDigital/personal-demographics-service-api)

    ## Technology
    This API is [RESTful](https://digital.nhs.uk/developer/developer-reference/introduction-to-apis#basic-rest).

    It also conforms to the [FHIR](https://digital.nhs.uk/developer/developer-reference/introduction-to-apis#fhir) global standard for health care data exchange.
    Specifically, it is aligned with [FHIR UK Core](https://digital.nhs.uk/services/fhir-uk-core), which is built on FHIR Release 4.

    You donâ€™t need to know much about FHIR to use this API - FHIR APIs are just RESTful APIs that follow specific rules.
    In particular:
    - resource names are capitalised and singular, for example the `/Patient` not `/patients`
    - array names are singular, for example `line` not `lines` for address lines
    - data items that are country-specific and thus not included in the FHIR global base resources are usually wrapped in an `extension` object

    ## Endpoints
    To see details for specific endpoints, select from the list on the left hand side of the page:
    * `GET /Patient` - search for patient
    * `GET /Patient/{id}` - get patient's personal details
    * `PATCH /Patient/{id}` - update patient's personal details

  contact:
    name: National Integration Adaptors API Support
    url: 'https://github.com/nhsconnect/integration-adaptors'
servers:
  - url: 'https://localhost'
    description: There are not publicly available services available for testing or integration
tags:
  - name: patients
paths:
  '/Patient/{id}/$nhais.deduction':
    parameters:
      - $ref: '#/components/parameters/Id'
    post:
      description: |
        ## Overview
        Use this endpoint to send a Deduction transaction to NHAIS.

        ## Operation Id
        When you submit an amendment an operation id will be included in the response. This operation id MUST be retained
        to match against the asynchronous reply from NHAIS

        ## EDIFACT

        The following Interchange contains just one Deduction Request transaction for:

        NHS Number N/10/10.
        Deduction Date : 25/12/1991, Deduction Reason : Death, Free Text : Died on holiday in Majorca.
        Registered with GP 281 (GMC National GP Code 4826940).

        Information transmitted within Interchange 2, Message 3, Transaction Number 17 at 13:17 on 13/01/1992.

        | EDIFACT                                    | Notes                                                           |
        |--------------------------------------------|-----------------------------------------------------------------|
        | UNB+UNOA:2+TES5+XX11+920113:1317+00000002' | SIS 00000002 generated by adaptor, abstracted by operation id, timestamp must match DTM |
        | UNH+00000003+FHSREG:0:1:FH:FHS001'         | SMS 00000003 generated by adaptor, abstracted by operation id   |
        | BGM+++507'                                 | n/a for API                                                     |
        | NAD+FHS+XX1:954'                           | XX1 is the cypher of the HA. Supplied by managingOrganization.identifier[0].value in the request body |
        | DTM+137:199201131317:203'                  | Timestamp of translation, adaptor will generate this            |
        | RFF+950:G5'                                | The transaction type G5 is used for all $nhais.deduction operations |
        | S01+1'                                     | n/a for API                                                     |
        | RFF+TN:17'                                 | Transaction id generated by adaptor, abstracted by operation id |
        | NAD+GP+4826940,281:900'                    | GMC Code: 4826940, Local Code: 281. Supplied by generalPractitioner[].value in the request body. |
        | GIS+1:ZZZ'                                 | Can be: 1 - Death, 5 - Emigrated, 13 - Other reason        TODO |
        | DTM+961:19911225:102'                      | 961 indicates this is a date of deduction                  TODO |
        | FTX+RGI+++DIED ON HOLIDAY IN MAJORCA'      | Free text deduction reason                                 TODO |
        | S02+2'                                     | n/a for API                                                     |
        | PNA+PAT+N/10/10:OPI'                       | N/10/10 is the NHS Number. Suppied by identifier[0].value (see examples) |
        | UNT+14+00000003'                           | n/a for API                                                     |
        | UNZ+1+00000002'                            | n/a for API                                                     |

        *TODO*: No UK Core representation of an HA, we need to define this ourselves
        *TODO*: No UK Core representations of GMC or local code, we need to define this ourselves
        *TODO*: Create a deductionDetails extension for patient

        ## Sandbox test scenarios
        *TODO*: document interactions supported by fake mesh

        | Scenario                            | Request                                                      | Response                                         |
        | ----------------------------------- | ------------------------------------------------------------ | ------------------------------------------------ |
        |                                     |                                                              |                                                  |

      summary: Deduct a patient (Deduction transaction)
      operationId: deduct-patient
      tags:
        - patients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: components/schemas/Patient.yaml
            examples:
              deduction-death:
                summary: Deduction - Death
                value:
                  $ref: components/examples/requests/NHAIS/deduction-death.json
              deduction-emigrated:
                summary: Deduction - Emigrated
                value:
                  $ref: components/examples/requests/NHAIS/deduction-emigrated.json
              deduction-other:
                summary: Deduction - Other
                value:
                  $ref: components/examples/requests/NHAIS/deduction-other.json
      responses:
        '202':
          description: Deduction forwarded to NHAIS for processing
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              examples:
                deduction-response:
                  summary: Deduction - response with operation id
                  value:
                    $ref: components/examples/responses/with-operation-id.json
        '400':
          description: Client error.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              examples:
                invalid-nhs-number:
                  summary: Invalid NHS number supplied
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: INVALID_NHS_NUMBER
                              display: NHS Number 9000000000 is not a valid NHS number.
                no-patches-submitted:
                  summary: No patches submitted
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: required
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: noPatchesSubmitted
                              display: No patches submitted.
                invalid-patch-operation:
                  summary: Invalid patch operation(s)
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: invalidPatchOperation
                              display: 'Invalid patch: attempted to modify Patient properties that cannot be changed by an Amendment'
        '415':
          description: Unsupported media type.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: value
                    details:
                      coding:
                        - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                          version: '1'
                          code: unsupportedMediaType
                          display: "Must be 'application/json-patch+json'."
  '/Patient/{id}/$nhais.removal':
    parameters:
      - $ref: '#/components/parameters/Id'
    post:
      description: |
        ## Overview
        Use this endpoint to send a Removal transaction to NHAIS.

        ## Operation Id
        TODO: operation id (transaction id) will probably need to be provided in the request since this is a reply to
        a HA -> GP amendment

        ## EDIFACT

        The following Interchange contains one Acceptance transaction - a Type 1 (Birth) Acceptance
        - one Amendment transaction and one Removal (Out of Area) transaction as follows:

        Acceptance for Mr. Peter Martin Stevens, NHS Number ACE99A999.
        Born : 07/12/1991 in Bury.
        Address : Middle Farm, New Street, St Pauls Cray, Orpington, Kent, BR1 5ER.
        Registered with GP 281 (GMC National GP Code 4826940).

        Amendment for NHS Number ABCDE1234.
        New Address : Flat 1a Spencer House, Card Road, St Pauls Cray, Orpington, Kent.
        Registered with GP 281 (GMC National GP Code 4826940).

        Removal (Out of Area) for NHS Number T247.
        Reason for Removal : PATIENT NOW LIVES 24 MILES FROM PRACTICE
        Registered with GP 281 (GMC National GP Code 4826940).

        Information transmitted within Interchange 8, Messages 9 to 11, Transaction Numbers 24 to 26 at 10:21 on 17/01/1992.

        | EDIFACT                                    | Notes                                                           |
        |--------------------------------------------|-----------------------------------------------------------------|
        | UNB+UNOA:2+TES5+XX11+920117:1021+00000008' | SIS 00000002 generated by adaptor, abstracted by operation id, timestamp must match DTM
        | UNH+00000011+FHSREG:0:1:FH:FHS001'         | SMS 00000003 generated by adaptor, abstracted by operation id
        | BGM+++507'                                 | n/a for API
        | NAD+FHS+XX1:954'                           | XX1 is the cypher of the HA. Supplied by managingOrganization.identifier[0].value in the request body
        | DTM+137:199201171259:203'                  | TODO: expectation is this == timestamp in UNB but this example is different
        | RFF+950:G3'                                | "G3" = GP to FHSA removal is used for all $nhais.removal operations
        | S01+1'                                     | n/a for API
        | RFF+TN:26'                                 | Transaction id generated by adaptor, abstracted by operation id |
        | NAD+GP+4826940,281:900'                    | GMC Code: 4826940, Local Code: 281. Supplied by generalPractitioner[].value in the request body. |
        | FTX+RGI+++PATIENT NOW LIVES 24 MILES FROM PRACTICE' | Free text deduction reason                                 TODO |
        | S02+2'                                     | n/a for API
        | PNA+PAT+T247:OPI'                          | T247 is the NHS Number. Suppied by identifier[0].value (see examples)
        | UNT+12+00000011'                           | n/a for API
        | UNZ+3+00000008'                            | n/a for API


        ## Sandbox test scenarios
        TODO: document interactions supported by fake mesh

        | Scenario                            | Request                                                      | Response                                         |
        | ----------------------------------- | ------------------------------------------------------------ | ------------------------------------------------ |
        |                                     |                                                              |                                                  |

      summary: Accept a new patient (Acceptance transaction)
      operationId: remove-patient
      tags:
        - patients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: components/schemas/Patient.yaml
            examples:
              removal:
                summary: Removal transaction
                value:
                  $ref: components/examples/requests/NHAIS/removal.json
      responses:
        '202':
          description: Removal forwarded to NHAIS for processing
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              examples:
                removal-response:
                  summary: Removal - response with operation id
                  value:
                    $ref: components/examples/responses/with-operation-id.json
        '400':
          description: Client error.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              examples:
                invalid-nhs-number:
                  summary: Invalid NHS number supplied
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: INVALID_NHS_NUMBER
                              display: NHS Number 9000000000 is not a valid NHS number.
                no-patches-submitted:
                  summary: No patches submitted
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: required
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: noPatchesSubmitted
                              display: No patches submitted.
                invalid-patch-operation:
                  summary: Invalid patch operation(s)
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: invalidPatchOperation
                              display: 'Invalid patch: attempted to modify Patient properties that cannot be changed by an Amendment'
        '415':
          description: Unsupported media type.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: value
                    details:
                      coding:
                        - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                          version: '1'
                          code: unsupportedMediaType
                          display: "Must be 'application/json-patch+json'."
  '/Patient/{id}':
    parameters:
      - $ref: '#/components/parameters/Id'
    post:
      description: |
        ## Overview
        Use this endpoint to send an Acceptance to NHAIS.

        It is anticipated that the GP System will prompt the GP to determine the following minimum basic information about the patient:
        		NHS Number
        	*	Surname
        		Previous Surname
        		Forename(s)
        		Title
        	*	Sex
        		Date of Birth
        	*	Present Address excluding Postcode
        		Postcode
        		Place of Birth [mandatory if NHS Number not entered]
        	*	Patient's Responsible GP
        	*	Patient's Responsible HA

        	(* = Mandatory field)

            Birth Acceptance:

            *	Patient's Responsible GP
        	*	Patient's Responsible HA
        	*	NHS Number
        	*	Surname
        		Previous Surname
        		First Forename
        		Second Forename
        		Other Forenames
        		Title
        	*	Sex
        	*	Date of Birth
        	*	Present Address excluding Postcode
        		Postcode
        		Place of Birth
        		Drugs Dispensed Marker
        		RPP Mileage
        		Blocked Route/Special District Marker
        		Walking Units
        		Residential Institute Code
        		Free Text (GP Notes)

        	(* = Mandatory field)

            1st Acceptance Acceptance:
            	*	Patient's Responsible GP
            	*	Patient's Responsible HA
            		NHS Number
            	*	Surname
            		Previous Surname
            		First Forename
            		Second Forename
            		Other Forenames
            		Title
            	*	Sex
            		Date of Birth
            	*	Present Address excluding Postcode
            		Postcode
            		Place of Birth [mandatory if NHS Number not entered]
            		Drugs Dispensed Marker
            		RPP Mileage
            		Blocked Route/Special District Marker
            		Walking Units
            		Residential Institute Code
            		Free Text (GP Notes)

            	(* = Mandatory field)

            Transfer In Acceptance:
            	*	Patient's Responsible GP
            	*	Patient's Responsible HA
            		NHS Number
            	*	Surname
            		Previous Surname
            		First Forename
            		Second Forename
            		Other Forenames
            		Title
            	*	Sex
            		Date of Birth
            	*	Present Address excluding Postcode
            		Postcode
            		Place of Birth [mandatory if NHS Number not entered]
            		Drugs Dispensed Marker
            		RPP Mileage
            		Blocked Route/Special District Marker
            		Walking Units
            		Residential Institute Code
            	*	Previous Address - 5 fields
            	*	Previous GP Name
            		Previous HA Cipher
            		Free Text (GP Notes)

            	(* = Mandatory field: for Previous Address at least one of the five fields MUST be completed.)

            Immigrant Acceptance:
            	*	Patient's Responsible GP
            	*	Patient's Responsible HA
            		NHS Number
            	*	Surname
            		Previous Surname
            		First Forename
            		Second Forename
            		Other Forenames
            		Title
            	*	Sex
            		Date of Birth
            	*	Present Address excluding Postcode
            		Postcode
            		Place of Birth [mandatory if NHS Number not entered]
            		Drugs Dispensed Marker
            		RPP Mileage
            		Blocked Route/Special District Marker
            		Walking Units
            		Residential Institute Code
            	*	Date of Entry into the UK
            		Date Patient left the UK
            		Previous Address - 5 fields
            		Previous GP Name
            		Previous HA Cipher
            		Free Text (GP Notes)

            	(* = Mandatory field)

            Ex-Services Acceptance:
            	*	Patient's Responsible GP
            	*	Patient's Responsible HA
            		NHS Number
            	*	Surname
            		Previous Surname
            		First Forename
            		Second Forename
            		Other Forenames
            		Title
            	*	Sex
            		Date of Birth
            	*	Present Address excluding Postcode
            		Postcode
            		Place of Birth [mandatory if NHS Number not entered]
            		Drugs Dispensed Marker
            		RPP Mileage
            		Blocked Route/Special District Marker
            		Walking Units
            		Residential Institute Code
            		Previous Address - 5 fields
            		Date of Enlistment (Joining)
            		Date of Enlistment (Leaving)
            		Free Text (GP Notes)

            	(* = Mandatory field)




        ## Operation Id
        When you submit an amendment an operation id will be included in the response. This operation id MUST be retained
        to match against the asynchronous reply from NHAIS

        ## Sandbox test scenarios
        TODO: document interactions supported by fake mesh

        | Scenario                            | Request                                                      | Response                                         |
        | ----------------------------------- | ------------------------------------------------------------ | ------------------------------------------------ |
        |                                     |                                                              |                                                  |

      summary: Accept a new patient (Acceptance transaction)
      operationId: accept-patient
      tags:
        - patients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: components/schemas/Patient.yaml
            examples:
              acceptance:
                summary: Acceptance transaction
                value:
                  $ref: components/examples/requests/NHAIS/acceptance.json
      responses:
        '202':
          description: Acceptance forwarded to NHAIS for processing
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
        '400':
          description: Client error.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              examples:
                invalid-nhs-number:
                  summary: Invalid NHS number supplied
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: INVALID_NHS_NUMBER
                              display: NHS Number 9000000000 is not a valid NHS number.
                no-patches-submitted:
                  summary: No patches submitted
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: required
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: noPatchesSubmitted
                              display: No patches submitted.
                invalid-patch-operation:
                  summary: Invalid patch operation(s)
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: invalidPatchOperation
                              display: 'Invalid patch: attempted to modify Patient properties that cannot be changed by an Amendment'
        '415':
          description: Unsupported media type.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: value
                    details:
                      coding:
                        - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                          version: '1'
                          code: unsupportedMediaType
                          display: "Must be 'application/json-patch+json'."
    patch:
      description: |
        ## Overview
        Use this endpoint to send an Amendment to NHAIS.

        This is a 'patch' operation, meaning you can update specific parts of the patient record (such as a name or an address), as opposed to having to update the entire record.

        ## Operation Id
        When you submit an amendment an operation id will be included in the response. This operation id MUST be retained
        to match against the asynchronous reply from NHAIS

        ## EDIFACT

        The following Interchange contains two Amendment transactions for:

        NHS Number SEQ12.
        New Title : Mrs.
        New Surname : Patterson.
        New Previous Surname : Smythe.
        New Address : Holly Cottage, 12 Long Lane, Bromley, Kent, BR5 4ER.
        Registered with GP 295 (GMC National GP Code 2750922) - now a dispensing GP for this patient.
        New Address has an RPP Mileage of  7, a Special District classification, Walking Units of 6 and a Residential Institute Code of AA.
        The GP has added some free text (GP Notes) at the time of registration.

        NHS Number 123/23/123.
        New Address : Flat 49, 23 Jackson Square, St Pauls Cray, Orpington, Kent.
        Registered with GP 281 (GMC National GP Code 4826940).
        New Address no longer has RPP Mileage, Blocked Route/Special District Classification or Walking Units.

        Information transmitted within Interchange 7, Message 8, Transaction Numbers 22 and 23 at 15:29 on 16/01/1992.

        | EDIFACT                                    | Notes                                                           |
        |--------------------------------------------|-----------------------------------------------------------------|
        | UNB+UNOA:2+TES5+XX11+920116:1529+00000007' | SIS 00000007 generated by adaptor, abstracted by operation id, timestamp is when message was translated
        | UNH+00000008+FHSREG:0:1:FH:FHS001'         | SMS 00000008 generated by adaptor, abstracted by operation id
        | BGM+++507'                                 | n/a for API
        | NAD+FHS+XX1:954'                           | XX1 is the cypher of the HA. Supplied by managingOrganization.identifier[0].value in the request body
        | DTM+137:199201171259:203'                  | TODO: expectation is this == timestamp in UNB but this example is different
        | RFF+950:G2'                                | "G3" = GP to FHSA amendment is used for all PATCH operations
        | S01+1'                                     | n/a for API
        | RFF+TN:22'                                 | Transaction id generated by adaptor, abstracted by operation id
        | NAD+GP+2750922,295:900'                    | GMC Code: 4826940, Local Code: 281. Supplied by       TBD
        | NAD+RIC+AA:956'                            | Residential Institute Code         TBD
        | QTY+951:7'
        | QTY+952:6'
        | HEA+BM+S:ZZZ'
        | HEA+DM+Y:ZZZ'
        | FTX+RGI+++NOW AT THE ARTHUR ANDREWS CENTRE'
        | S02+2'
        | PNA+PAT+SEQ12:OPI+++SU:PATTERSON++TI:MRS'
        | NAD+PAT++HOLLY COTTAGE:12 LONG LANE::BROMLEY:KENT+++++BR5  4ER'
        | S02+2'
        | PNA+PER++++SU:SMYTHE'
        | S01+1'
        | RFF+TN:23'
        | NAD+GP+4826940,281:900'
        | QTY+951:%'
        | QTY+952:%'
        | HEA+BM+%:ZZZ'
        | S02+2'
        | PNA+PAT+123/23/123:OPI'
        | NAD+PAT++FLAT 49:23 JACKSON SQUARE:ST PAULS CRAY:ORPINGTON:KENT'
        | UNT+29+00000008'
        | UNZ+1+00000007'




        ## Sandbox test scenarios
        TODO: document interactions supported by fake mesh

        | Scenario                            | Request                                                      | Response                                         |
        | ----------------------------------- | ------------------------------------------------------------ | ------------------------------------------------ |
        |                                     |                                                              |                                                  |

      summary: Amend patient details (Amendment transaction)
      operationId: update-patient-partial
      tags:
        - patients
      externalDocs:
        description: IETF RFC 6902, which defines json-patch.
        url: https://tools.ietf.org/html/rfc6902
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - patches
              properties:
                correction:
                  description: Set to true if the update is correcting previously incorrect data.
                  type: boolean
                  default: false
                patches:
                  $ref: components/schemas/JsonPatch.yaml
            examples:
              amendment:
                summary: Amendment transaction
                value:
                  $ref: components/examples/requests/PatientPatch/amendment.json
      responses:
        '202':
          description: Amendment forwarded to NHAIS for processing
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
        '400':
          description: Client error.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              examples:
                invalid-nhs-number:
                  summary: Invalid NHS number supplied
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: INVALID_NHS_NUMBER
                              display: NHS Number 9000000000 is not a valid NHS number.
                no-patches-submitted:
                  summary: No patches submitted
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: required
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: noPatchesSubmitted
                              display: No patches submitted.
                invalid-patch-operation:
                  summary: Invalid patch operation(s)
                  value:
                    resourceType: OperationOutcome
                    issue:
                      - severity: error
                        code: value
                        details:
                          coding:
                            - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                              version: '1'
                              code: invalidPatchOperation
                              display: 'Invalid patch: attempted to modify Patient properties that cannot be changed by an Amendment'
        '415':
          description: Unsupported media type.
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: value
                    details:
                      coding:
                        - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                          version: '1'
                          code: unsupportedMediaType
                          display: "Must be 'application/json-patch+json'."
components:
  parameters:
    Id:
      name: id
      in: path
      description: The patient's NHS Number. The primary identifier of a patient, unique within NHS England and Wales. Always 10 digits and must be a [valid NHS Number](https://www.datadictionary.nhs.uk/data_dictionary/attributes/n/nhs/nhs_number_de.asp).
      required: true
      schema:
        type: string
        example: "9000000009"
  schemas:
    Patient:
      $ref: components/schemas/Patient.yaml
    OperationOutcome:
      $ref: components/schemas/OperationOutcome.yaml
